#!/usr/bin/env python3
# add_test_agent.py - Class-Based Prompt Flow for --add-test
#
# Implements the spec "Gateway Serial Test Framework - AI Test-Add Agent -
# Class-Based Prompt Flow". Collects TestCase / TestSuite / registration
# fields via a short Q&A session and appends generated code to
# custom_tests.py, matching the pattern a developer would hand-write in
# tests.py.
#
# Usage: python3 main.py --add-test
# Full example session: see "Method 3" under CUSTOMIZATION in Documentation.md

import os
import re
import py_compile
from datetime import datetime

CUSTOM_TESTS_FILE = "custom_tests.py"

CUSTOM_TESTS_HEADER = '''#!/usr/bin/env python3
# custom_tests.py - Auto-generated custom tests
#
# Generated by the --add-test agent. Each block below defines a TestCase,
# wraps it in a TestSuite, and registers it in TEST_SUITES, exactly as you
# would by hand in tests.py.

from tests import TestCase, TestSuite, TEST_SUITES
'''


# ======================= VALIDATION HELPERS =======================

def to_snake_case(raw: str) -> str:
    """Lowercase, spaces/dashes -> underscores, strip invalid characters."""
    s = raw.strip().lower()
    s = re.sub(r'[\s\-]+', '_', s)
    s = re.sub(r'[^a-z0-9_]', '', s)
    s = re.sub(r'_+', '_', s).strip('_')
    return s


def existing_registration_keys():
    """Read registration keys already present in tests.py and custom_tests.py."""
    keys = set()
    try:
        from tests import TEST_SUITES as BASE_SUITES
        keys.update(BASE_SUITES.keys())
    except Exception:
        pass

    if os.path.exists(CUSTOM_TESTS_FILE):
        try:
            with open(CUSTOM_TESTS_FILE, 'r', encoding='utf-8') as f:
                content = f.read()
            keys.update(re.findall(r'TEST_SUITES\["([^"]+)"\]\s*=', content))
        except Exception:
            pass

    return keys


# ======================= STEP 1: TESTCASE =======================

def collect_testcase():
    print("\n" + "=" * 60)
    print("STEP 1 - TestCase fields")
    print("=" * 60)

    # Test name (snake_case), reject empty
    while True:
        raw_name = input("Test name (snake_case): ").strip()

        if not raw_name:
            print("[!] Test name cannot be empty.")
            continue

        name = to_snake_case(raw_name)

        if not name:
            print("[!] Test name has no valid characters after cleanup, try again.")
            continue

        if name != raw_name:
            print(f"[*] Normalized to snake_case: {name}")

        break

    # Shell command, reject empty
    while True:
        command = input(
            'Shell command (e.g. pcb_cli "NMC.getWanModeList()"): '
        ).strip()

        if not command:
            print("[!] Command cannot be empty.")
            continue

        break

    # Description
    description = input(
        f"Description (one line) [Run {name}]: "
    ).strip()

    if not description:
        description = f"Run {name}"

    # Summary
    summary = input(
        f"Summary (short one-line summary) [Run {name}]: "
    ).strip()

    if not summary:
        summary = f"Run {name}"

    # Timeout
    while True:
        raw_timeout = input("Timeout in seconds [5]: ").strip()

        if not raw_timeout:
            timeout = 5
            break

        try:
            timeout = int(raw_timeout)

            if timeout <= 0:
                print("[!] Timeout must be a positive integer.")
                continue

            break

        except ValueError:
            print("[!] Timeout must be a positive integer.")

    # Expected output substring
    expected_output = input(
        "Expected output substring (blank = any output passes): "
    ).strip()

    if not expected_output:
        expected_output = None

    # Custom validator - only asked if expected_output is blank
    validate_func = None

    if expected_output is None:
        validate_func = input(
            "Custom validator? Free Python boolean expression on variable o "
            "(blank = skip): "
        ).strip()

        if not validate_func:
            validate_func = None

    return {
        "name": name,
        "command": command,
        "description": description,
        "summary": summary,
        "timeout": timeout,
        "expected_output": expected_output,
        "validate_func": validate_func,
    }

# ======================= STEP 2: TESTSUITE =======================

def collect_testsuite(testcase):
    print("\n" + "=" * 60)
    print("STEP 2 - TestSuite fields")
    print("=" * 60)

    suite_name = input(f"Suite name [{testcase['name']}]: ").strip()
    if not suite_name:
        suite_name = testcase["name"]

    suite_description = input(
        f"Suite description [{testcase['description']}]: "
    ).strip()
    if not suite_description:
        suite_description = testcase["description"]

    return {"name": suite_name, "description": suite_description}


# ======================= STEP 3: REGISTRATION =======================

def collect_registration(suite):
    print("\n" + "=" * 60)
    print("STEP 3 - Registration")
    print("=" * 60)

    taken_keys = existing_registration_keys()

    key = input(f'Key for the TEST_SUITES dict [{suite["name"]}]: ').strip()
    if not key:
        key = suite["name"]

    while key in taken_keys:
        print(f'[!] TEST_SUITES["{key}"] already exists.')
        choice = input(
            "    Enter a different key, or type 'overwrite' to confirm "
            "overwrite anyway: "
        ).strip()
        if choice.lower() == "overwrite":
            break
        elif choice:
            key = choice
        else:
            key = suite["name"]
    return key


# ======================= CODE GENERATION =======================

def generate_code(testcase, suite, registration_key):
    upper_name = testcase["name"].upper()
    testcase_var = f"TEST_{upper_name}"
    suite_var = f"{upper_name}_SUITE"

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = []
    lines.append(f"# {'=' * 60}")
    lines.append(f"# Test: {testcase['name']}")
    lines.append(f"# Generated: {timestamp}")
    lines.append(f"# summary={testcase['summary']!r},")
    lines.append(f"# {'=' * 60}")
    lines.append(f"{testcase_var} = TestCase(")
    lines.append(f"    name={testcase['name']!r},")
    lines.append(f"    command={testcase['command']!r},")
    lines.append(f"    description={testcase['description']!r},")
    lines.append(f"    timeout={testcase['timeout']},")
    
    # Mutually exclusive: validate_func takes priority over expected_output
    if testcase["validate_func"]:
        lines.append(f"    validate_func=lambda o: {testcase['validate_func']},")
    elif testcase["expected_output"]:
        lines.append(f"    expected_output={testcase['expected_output']!r},")

    lines.append(")")
    lines.append("")
    lines.append(f"{suite_var} = TestSuite(")
    lines.append(f"    name={suite['name']!r},")
    lines.append(f"    description={suite['description']!r},")
    lines.append(f"    tests=[{testcase_var}],")
    lines.append(")")
    lines.append("")
    lines.append(f'TEST_SUITES["{registration_key}"] = {suite_var}')
    lines.append("")

    return "\n".join(lines)


# ======================= FILE OUTPUT =======================

def append_to_file(code, path=CUSTOM_TESTS_FILE):
    """Append generated code to custom_tests.py, creating it if needed.
    Verifies the file still compiles after the append."""
    is_new = not os.path.exists(path)

    try:
        if is_new:
            with open(path, "w", encoding="utf-8") as f:
                f.write(CUSTOM_TESTS_HEADER)
                f.write("\n")
            print(f"[*] Created {path}")

        with open(path, "a", encoding="utf-8") as f:
            f.write("\n" + code + "\n")

    except Exception as e:
        print(f"[!] Error writing to {path}: {e}")
        return False

    # Compile check - must remain valid, importable Python
    try:
        py_compile.compile(path, doraise=True)
    except py_compile.PyCompileError as e:
        print(f"[!] {path} failed to compile after append: {e}")
        return False

    print(f"[+] {path} compiled successfully")
    return True


# ======================= MAIN FLOW =======================

def run_add_test_flow():
    """Entry point for `python3 main.py --add-test`."""
    print("\n" + "=" * 60)
    print("ADD TEST - Class-Based Prompt Flow")
    print("=" * 60)

    testcase = collect_testcase()
    suite = collect_testsuite(testcase)
    registration_key = collect_registration(suite)

    code = generate_code(testcase, suite, registration_key)

    print("\n" + "=" * 60)
    print("PREVIEW")
    print("=" * 60)
    print(code)
    print("=" * 60)

    confirm = input("Write this to custom_tests.py? [Y/n]: ").strip().lower()
    if confirm not in ("", "y", "yes"):
        print("[*] Cancelled - nothing written.")
        return

    if append_to_file(code):
        print(f"[+] Test '{testcase['name']}' added and registered "
              f"as \"{registration_key}\".")
    else:
        print("[!] Test was not saved cleanly. Check custom_tests.py.")


if __name__ == "__main__":
    run_add_test_flow()
