#!/usr/bin/env python3
# main.py - Generic Gateway Serial Connector

import serial
import time
import sys
import argparse
from datetime import datetime
import os
import signal
from typing import Optional, List, Dict, Any
import os
from dotenv import load_dotenv
# Import our modules
from config import get_config, GatewayConfig
from tests import get_test_suite, list_test_suites, get_test_suite_details
from tests import get_dslite_retry_executor, get_continuous_loop_executor, get_simple_loop_executor
from add_test_agent import run_add_test_flow
from ai_test_agent import run_add_test_ai_flow

# custom_tests.py is generated by --add-test. Import it (if present) so any
# tests it registers into TEST_SUITES are visible to --list-tests / --run.
try:
    import custom_tests  # noqa: F401 - imported for its registration side effect
except ImportError:
    pass

class GatewaySerialConnector:
    def __init__(self, config: Optional[GatewayConfig] = None):
        self.config = config or get_config()
        self.ser = None
        self.log_file = None
        self.is_connected = False
        
        signal.signal(signal.SIGINT, self.signal_handler)
    
    def signal_handler(self, sig, frame):
        print("\n[!] Interrupted by user")
        self.disconnect()
        sys.exit(0)
    
    def connect(self) -> bool:
        """Establish serial connection"""
        try:
            print(f"[*] Connecting to {self.config.port} at {self.config.baudrate} baud...")
            
            self.ser = serial.Serial(
                port=self.config.port,
                baudrate=self.config.baudrate,
                bytesize=serial.EIGHTBITS,
                parity=serial.PARITY_NONE,
                stopbits=serial.STOPBITS_ONE,
                timeout=self.config.timeout,
                xonxoff=False,
                rtscts=False,
                dsrdtr=False
            )
            
            self.ser.reset_input_buffer()
            self.ser.reset_output_buffer()
            
            time.sleep(2)
            
            # Wake up device
            self.ser.write(b'\r\n')
            time.sleep(1)
            
            print("[+] Serial connection established")
            self.is_connected = True
            return True
            
        except Exception as e:
            print(f"[!] Connection error: {e}")
            return False
    
    def open_log(self, filename: str) -> bool:
        """Open log file"""
        try:
            if os.path.exists(filename):
                timestamp = datetime.now().strftime(self.config.log_timestamp_format)
                name, ext = os.path.splitext(filename)
                filename = f"{name}_{timestamp}{ext}"
            
            self.log_file = open(filename, 'a', encoding='utf-8')
            print(f"[*] Logging to: {filename}")
            return True
        except Exception as e:
            print(f"[!] Error opening log file: {e}")
            return False
    
    def read_available(self, timeout: int = None, show: bool = True) -> str:
        """Read available data from serial"""
        if not self.is_connected or not self.ser:
            return ""
        
        timeout = timeout or self.config.prompt_timeout
        output = ""
        start_time = time.time()
        
        while time.time() - start_time < timeout:
            if self.ser.in_waiting > 0:
                data = self.ser.read(self.ser.in_waiting).decode('utf-8', errors='ignore')
                output += data
                
                if show:
                    sys.stdout.write(data)
                    sys.stdout.flush()
                
                if data and self.log_file:
                    self.log_file.write(data)
                    self.log_file.flush()
                
                # Reset timeout if we got data
                if data:
                    start_time = time.time()
            else:
                time.sleep(0.01)
        
        return output
    
    def send(self, data: str, wait: float = 0.5, echo: bool = True) -> bool:
        """Send data to serial"""
        if not self.is_connected or not self.ser:
            return False
        
        try:
            if not data.endswith('\n'):
                data += '\n'
            
            if echo:
                print(f"[>] {data.strip()}")
            
            if self.log_file:
                self.log_file.write(f"[TX] {data}")
                self.log_file.flush()
            
            self.ser.write(data.encode('utf-8'))
            self.ser.flush()
            
            time.sleep(wait)
            return True
            
        except Exception as e:
            print(f"[!] Send error: {e}")
            return False
    
    def login(self, force_new_login: bool = False, max_attempts: int = 3) -> bool:
        """Perform login with retry logic"""
        for attempt in range(1, max_attempts + 1):
            print(f"[*] Login attempt {attempt}/{max_attempts} as {self.config.username}...")
            
            # Read initial output to see where we are
            time.sleep(1)
            output = self.read_available(timeout=3, show=False)
            
            # If we're already at a shell prompt, we're already logged in
            for prompt in self.config.shell_prompts:
                if prompt in output:
                    print("[+] Already logged in")
                    return True
            
            # Check if we're at login prompt
            if "LIVEBOX login:" in output and not force_new_login:
                print("[*] At login prompt, proceeding with login")
            else:
                # We might need to send Enter to get login prompt
                print("[*] Sending Enter to get login prompt...")
                self.send('', wait=1, echo=False)
                time.sleep(2)
                output = self.read_available(timeout=3, show=False)
            
            # Clear any leftover output
            self.read_available(timeout=1, show=False)
            
            # Send username
            if not self.send(self.config.username, wait=1):
                print("[!] Failed to send username")
                if attempt < max_attempts:
                    time.sleep(2)
                    continue
                return False
            
            # Wait for password prompt
            time.sleep(1)
            output = self.read_available(timeout=3, show=False)
            
            if "Password:" not in output and "password" not in output.lower():
                print("[*] Password prompt not found, trying to send password anyway...")
            
            # Send password
            if not self.send(self.config.password, wait=2, echo=False):
                print("[!] Failed to send password")
                if attempt < max_attempts:
                    time.sleep(2)
                    continue
                return False
            
            # Wait for login and check for shell prompt
            time.sleep(3)
            output = self.read_available(timeout=5, show=False)
            
            # Check for shell prompt
            for prompt in self.config.shell_prompts:
                if prompt in output:
                    print("[+] Login successful")
                    return True
            
            # Try sending Enter to get prompt
            self.send('', wait=1, echo=False)
            time.sleep(1)
            output = self.read_available(timeout=3, show=False)
            
            for prompt in self.config.shell_prompts:
                if prompt in output:
                    print("[+] Login successful (after Enter)")
                    return True
            
            if attempt < max_attempts:
                print(f"[!] Login attempt {attempt} failed, waiting 2s before retry...")
                print(f"[*] Last output: {output[-100:] if len(output) > 100 else output}")
                time.sleep(2)
            else:
                print("[!] All login attempts failed")
                print(f"[*] Final output: {output[-200:] if len(output) > 200 else output}")
        
        return False
    
    def wait_for_login_prompt(self, timeout: int = 30) -> bool:
        """Wait for login prompt to appear (useful after reboot)"""
        print(f"[*] Waiting for login prompt (timeout: {timeout}s)...")
        
        start_time = time.time()
        while time.time() - start_time < timeout:
            # Send Enter to wake up prompt
            self.send('', wait=1, echo=False)
            time.sleep(1)
            
            output = self.read_available(timeout=3, show=False)
            
            if "LIVEBOX login:" in output:
                print("[+] Login prompt detected")
                return True
            
            # Also check if we're already at shell (in case auto-login)
            for prompt in self.config.shell_prompts:
                if prompt in output:
                    print("[+] Already at shell prompt")
                    return True
            
            time.sleep(2)
        
        print("[!] Login prompt not detected within timeout")
        return False
    
    def execute_command(self, command: str, timeout: int = None) -> Dict[str, Any]:
        """Execute a single command"""
        timeout = timeout or self.config.command_timeout
        
        print(f"\n{'='*60}")
        print(f"Command: {command}")
        print('='*60)
        
        # Send command
        if not self.send(command, wait=0.5):
            return {"success": False, "output": "", "error": "Failed to send command"}
        
        # Read output
        time.sleep(0.5)
        output = self.read_available(timeout=timeout, show=True)
        
        # Ensure we get a prompt
        if not any(prompt in output[-20:] for prompt in self.config.shell_prompts):
            self.send('', wait=0.5, echo=False)
            time.sleep(0.5)
            output += self.read_available(timeout=2, show=True)
        
        print('='*60)
        
        return {
            "success": True,
            "command": command,
            "output": output,
            "timestamp": datetime.now().isoformat()
        }
    
    def run_tests(self, test_suite_name: str) -> Dict[str, Any]:
        """Run a test suite"""
        test_suite = get_test_suite(test_suite_name)
        if not test_suite:
            return {"success": False, "error": f"Test suite '{test_suite_name}' not found"}
        
        print(f"\n{'='*60}")
        print(f"Running test suite: {test_suite.name}")
        print(f"Description: {test_suite.description}")
        print(f"Tests: {len(test_suite.tests)}")
        print('='*60)
        
        results = {
            "suite_name": test_suite.name,
            "description": test_suite.description,
            "timestamp": datetime.now().isoformat(),
            "tests": [],
            "summary": {
                "total": 0,
                "passed": 0,
                "failed": 0
            }
        }
        
        # Run setup commands if any
        if test_suite.setup_commands:
            print("\n[*] Running setup commands...")
            for cmd in test_suite.setup_commands:
                self.execute_command(cmd, timeout=2)
        
        # Run each test
        for test in test_suite.tests:
            print(f"\n[+] Test: {test.name}")
            print(f"    Command: {test.command}")
            if test.description:
                print(f"    Description: {test.description}")
            
            # Wait if specified
            if test.wait_before > 0:
                time.sleep(test.wait_before)
            
            # Execute command
            result = self.execute_command(test.command, timeout=test.timeout)
            
            # Process result with filter if available
            filtered_result = None
            if hasattr(test, 'result_filter') and test.result_filter:
                try:
                    filtered_result = test.result_filter(result["output"])
                    print(f"    Filtered Result: {filtered_result}")
                except Exception as e:
                    print(f"    [!] Error in result filter: {e}")
                    filtered_result = {"error": str(e)}
            
            # Save result to file using test's save method
            if hasattr(test, 'save_result_to_file'):
                test.save_result_to_file(result["output"], filtered_result)
            
            # Validate
            is_valid = test.validate(result["output"])
            status = "PASS" if is_valid else "FAIL"
            
            print(f"    Result: {status}")
            
            # Store result
            test_result = {
                "name": test.name,
                "command": test.command,
                "output": result["output"],
                "filtered_result": filtered_result,
                "status": status,
                "valid": is_valid,
                "timestamp": result["timestamp"]
            }
            
            results["tests"].append(test_result)
            results["summary"]["total"] += 1
            if is_valid:
                results["summary"]["passed"] += 1
            else:
                results["summary"]["failed"] += 1
            
            # Wait if specified
            if test.wait_after > 0:
                time.sleep(test.wait_after)
        
        # Run teardown commands if any
        if test_suite.teardown_commands:
            print("\n[*] Running teardown commands...")
            for cmd in test_suite.teardown_commands:
                self.execute_command(cmd, timeout=2)
        
        # Print summary
        print(f"\n{'='*60}")
        print("TEST SUMMARY:")
        print(f"  Total:  {results['summary']['total']}")
        print(f"  Passed: {results['summary']['passed']}")
        print(f"  Failed: {results['summary']['failed']}")
        print('='*60)
        
        results["success"] = results["summary"]["failed"] == 0
        return results
    
    def interactive_mode(self):
        """Start interactive mode"""
        print("\n" + "="*60)
        print("INTERACTIVE MODE")
        print("="*60)
        print("Type commands to execute on gateway")
        print("Type 'exit' to quit")
        print("Type 'tests' to list available test suites")
        print("Type 'run <suite>' to run a test suite")
        print("="*60 + "\n")
        
        while True:
            try:
                user_input = input("\n[gw]# ").strip()
                
                if not user_input:
                    continue
                
                if user_input.lower() == 'exit':
                    print("[*] Exiting interactive mode...")
                    break
                
                elif user_input.lower() == 'tests':
                    print("\nAvailable test suites:")
                    for name, details in get_test_suite_details().items():
                        print(f"  {name}: {details['description']} ({details['test_count']} tests)")
                
                elif user_input.lower().startswith('run '):
                    suite_name = user_input[4:].strip()
                    self.run_tests(suite_name)
                
                else:
                    self.execute_command(user_input, timeout=5)
                    
            except KeyboardInterrupt:
                print("\n[*] Exiting interactive mode...")
                break
            except EOFError:
                print("\n[*] Exiting...")
                break
            except Exception as e:
                print(f"[!] Error: {e}")
    
    def disconnect(self):
        """Close connection"""
        if self.ser and self.is_connected:
            try:
                self.send('exit', wait=0.5, echo=False)
                time.sleep(1)
                self.ser.close()
                print("[*] Serial connection closed")
            except:
                pass
            
            self.is_connected = False
        
        if self.log_file:
            try:
                self.log_file.write(f"\n{'='*60}\n")
                self.log_file.write(f"Session ended: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                self.log_file.write(f"{'='*60}\n")
                self.log_file.close()
                print(f"[*] Log file closed")
            except:
                pass

def main():
    parser = argparse.ArgumentParser(
        description='Gateway Serial Console with Testing',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s                           # Interactive mode
  %(prog)s --list-tests              # List available test suites
  %(prog)s --add-test                # Interactively add a new test to custom_tests.py
  %(prog)s --run basic               # Run basic test suite
  %(prog)s --run dslite_full         # Run DSLITE comprehensive test
  %(prog)s --run wan_status          # Check WAN status
  %(prog)s --dslite-retry            # Run DSLITE test with retry logic
  %(prog)s --continuous-loop         # Run continuous test loop
  %(prog)s --simple-loop             # Run simple test loop
  %(prog)s --max-loops 10            # Run maximum 10 loops
  %(prog)s -c "uptime"               # Run single command
  %(prog)s -o output.log             # Log output to file
  %(prog)s -p /dev/ttyUSB1           # Use different port
        """
    )
    
    parser.add_argument('-p', '--port',
                       help='Serial port (overrides config)')
    
    parser.add_argument('-b', '--baud',
                       type=int,
                       help='Baud rate (overrides config)')
    
    parser.add_argument('-c', '--command',
                       help='Single command to execute')
    
    parser.add_argument('-o', '--output',
                       help='Log output to file')
    
    parser.add_argument('--config',
                       default='default',
                       help='Configuration profile (default, livebox, fast, debug)')
    
    parser.add_argument('--list-tests',
                       action='store_true',
                       help='List available test suites and exit')

    parser.add_argument('--add-test',
                       action='store_true',
                       help='Interactively add a new test (TestCase/TestSuite) to custom_tests.py and exit')

    parser.add_argument('--add-test-ai',
                       action='store_true',
                       help='Add a new test using natural language (Groq AI extraction) and exit')
    
    parser.add_argument('--run',
                       help='Run a test suite by name')
    
    parser.add_argument('--no-login',
                       action='store_true',
                       help='Skip automatic login')
    
    parser.add_argument('-i', '--interactive',
                       action='store_true',
                       help='Start interactive mode (default if no other action)')
    
    parser.add_argument('--dslite-retry',
                       action='store_true',
                       help='Run DSLITE comprehensive test with retry logic')
    
    parser.add_argument('--max-attempts',
                       type=int,
                       default=30,
                       help='Max attempts for retry tests (default: 30)')
    
    parser.add_argument('--retry-delay',
                       type=int,
                       default=10,
                       help='Delay between retry attempts in seconds (default: 10)')
    
    parser.add_argument('--continuous-loop',
                       action='store_true',
                       help='Run continuous test loop sequence with reset_hard')
    
    parser.add_argument('--simple-loop',
                       action='store_true',
                       help='Run simple test loop (no reset_hard)')
    
    parser.add_argument('--max-loops',
                       type=int,
                       default=None,
                       help='Maximum number of loops to run')
    
    args = parser.parse_args()
    
    # Add a new test interactively if requested (no gateway connection needed)
    if args.add_test:
        run_add_test_flow()
        return

    # Add a new test via AI-assisted natural language extraction
    if args.add_test_ai:
        run_add_test_ai_flow()
        return

    # List tests if requested
    if args.list_tests:
        print("Available test suites:")
        print("-" * 60)
        for name, details in get_test_suite_details().items():
            print(f"{name:20} - {details['description']}")
            print(f"{' ':22}Tests: {', '.join(details['tests'])}")
            print()
        return
    
    # Get configuration
    config = get_config(args.config)
    
    # Override config with command line arguments
    if args.port:
        config.port = args.port
    if args.baud:
        config.baudrate = args.baud
    
    # Create connector
    connector = GatewaySerialConnector(config)
    
    try:
        # Connect
        if not connector.connect():
            sys.exit(1)
        
        # Open log file if specified
        if args.output:
            connector.open_log(args.output)
        
        # Login unless disabled
        if not args.no_login:
            connector.login()
        
        # Determine action
        if args.continuous_loop:
            # Run continuous loop with reset_hard
            loop_executor = get_continuous_loop_executor(args.max_loops)
            loop_executor(connector)
        
        elif args.simple_loop:
            # Run simple loop (no reset_hard)
            loop_executor = get_simple_loop_executor(args.max_loops)
            loop_executor(connector)
        
        elif args.dslite_retry:
            # Run DSLITE test with retry logic
            dslite_executor = get_dslite_retry_executor(
                max_attempts=args.max_attempts,
                delay_seconds=args.retry_delay
            )
            dslite_executor(connector)
        
        elif args.run:
            # Run test suite
            connector.run_tests(args.run)
        
        elif args.command:
            # Execute single command
            connector.execute_command(args.command)
        
        elif args.interactive or (not args.continuous_loop and not args.simple_loop and 
                                 not args.dslite_retry and not args.run and not args.command):
            # Interactive mode (default)
            connector.interactive_mode()
        
    except Exception as e:
        print(f"[!] Error: {e}")
        import traceback
        traceback.print_exc()
    finally:
        connector.disconnect()

if __name__ == "__main__":
    main()